# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bda5e11e2815727eacc764ba6d66ec0ec4a6978c5b1301556b50e9d1fbcdf021b41dff4c242f48839b4bb35e3797295f40f1a30df5699fbe2441647ee618af72

test:
  secret_key_base: f65a2a28258c80b01ee8f55e8cf4f6b9965d8ec2fdf6604c04ef27486a6f1d22ab649de45a5d0a37a33af02053e6b59e85047da6ad652d351ae8235ff4809593

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
